ALTER TABLE RM_ENVIRONMENT MODIFY COLUMN ID INTEGER auto_increment;

ALTER TABLE RM_SERVER_INSTANCE MODIFY COLUMN ID INTEGER auto_increment;
ALTER TABLE RM_SERVER_INSTANCE MODIFY ADMIN_PASSWORD VARCHAR(255);
ALTER TABLE RM_SERVER_INSTANCE ADD COLUMN DRIVER_CLASS VARCHAR(128) NOT NULL;
ALTER TABLE RM_SERVER_INSTANCE ADD COLUMN SSH_HOST VARCHAR(128);
ALTER TABLE RM_SERVER_INSTANCE ADD COLUMN SSH_PORT INTEGER;
ALTER TABLE RM_SERVER_INSTANCE ADD COLUMN SSH_USERNAME VARCHAR(128);
ALTER TABLE RM_SERVER_INSTANCE ADD COLUMN SNAPSHOT_TARGET_DIRECTORY VARCHAR(1024);

ALTER TABLE RM_DATABASE MODIFY COLUMN ID INTEGER auto_increment;

ALTER TABLE RM_DATABASE_USER MODIFY COLUMN ID INTEGER auto_increment;
ALTER TABLE RM_DATABASE_USER ADD COLUMN RSS_INSTANCE_ID INTEGER NOT NULL DEFAULT -1;
ALTER TABLE RM_DATABASE_USER ADD CONSTRAINT UNQ_RM_DATABASE_USER_01 UNIQUE (USERNAME, TENANT_ID, ENVIRONMENT_ID, RSS_INSTANCE_ID);

ALTER TABLE RM_USER_DATABASE_ENTRY MODIFY COLUMN ID INTEGER auto_increment;

ALTER TABLE RM_USER_DATABASE_PRIVILEGE MODIFY COLUMN ID INTEGER auto_increment;

ALTER TABLE RM_SYSTEM_DATABASE_COUNT MODIFY COLUMN ID INTEGER auto_increment;

ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE MODIFY COLUMN ID INTEGER auto_increment;

ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE_ENTRY MODIFY COLUMN ID INTEGER auto_increment;






