CREATE SEQUENCE RM_ENVIRONMENT_SEQ;
ALTER TABLE RM_ENVIRONMENT ALTER COLUMN ID SET DEFAULT nextval('RM_ENVIRONMENT_SEQ');
ALTER TABLE RM_ENVIRONMENT ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_ENVIRONMENT_SEQ OWNED BY RM_ENVIRONMENT.ID; 
ALTER TABLE RM_ENVIRONMENT DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_SERVER_INSTANCE_SEQ;
ALTER TABLE RM_SERVER_INSTANCE ALTER COLUMN ID SET DEFAULT nextval('RM_SERVER_INSTANCE_SEQ');
ALTER TABLE RM_SERVER_INSTANCE ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_SERVER_INSTANCE_SEQ OWNED BY RM_SERVER_INSTANCE.ID; 
ALTER TABLE RM_SERVER_INSTANCE DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_DATABASE_SEQ;
ALTER TABLE RM_DATABASE ALTER COLUMN ID SET DEFAULT nextval('RM_DATABASE_SEQ');
ALTER TABLE RM_DATABASE ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_DATABASE_SEQ OWNED BY RM_DATABASE.ID; 
ALTER TABLE RM_DATABASE DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_DATABASE_USER_SEQ;
ALTER TABLE RM_DATABASE_USER ALTER COLUMN ID SET DEFAULT nextval('RM_DATABASE_USER_SEQ');
ALTER TABLE RM_DATABASE_USER ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_DATABASE_USER_SEQ OWNED BY RM_DATABASE_USER.ID; 
ALTER TABLE RM_DATABASE_USER ADD COLUMN RSS_INSTANCE_ID INTEGER NOT NULL DEFAULT -1;
ALTER TABLE RM_DATABASE_USER ADD CONSTRAINT UNQ_RM_DATABASE_USER_01 UNIQUE (USERNAME, TENANT_ID, ENVIRONMENT_ID, RSS_INSTANCE_ID);
ALTER TABLE RM_DATABASE_USER DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_USER_DATABASE_ENTRY_SEQ;
ALTER TABLE RM_USER_DATABASE_ENTRY ALTER COLUMN ID SET DEFAULT nextval('RM_USER_DATABASE_ENTRY_SEQ');
ALTER TABLE RM_USER_DATABASE_ENTRY ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_USER_DATABASE_ENTRY_SEQ OWNED BY RM_USER_DATABASE_ENTRY.ID; 
ALTER TABLE RM_USER_DATABASE_ENTRY DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_USER_DATABASE_PRIVILEGE_SEQ;
ALTER TABLE RM_USER_DATABASE_PRIVILEGE ALTER COLUMN ID SET DEFAULT nextval('RM_USER_DATABASE_PRIVILEGE_SEQ');
ALTER TABLE RM_USER_DATABASE_PRIVILEGE ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_USER_DATABASE_PRIVILEGE_SEQ OWNED BY RM_USER_DATABASE_PRIVILEGE.ID; 
ALTER TABLE RM_USER_DATABASE_PRIVILEGE DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_SYSTEM_DATABASE_COUNT_SEQ;
ALTER TABLE RM_SYSTEM_DATABASE_COUNT ALTER COLUMN ID SET DEFAULT nextval('RM_SYSTEM_DATABASE_COUNT_SEQ');
ALTER TABLE RM_SYSTEM_DATABASE_COUNT ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_SYSTEM_DATABASE_COUNT_SEQ OWNED BY RM_SYSTEM_DATABASE_COUNT.ID; 
ALTER TABLE RM_SYSTEM_DATABASE_COUNT DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_DB_PRIVILEGE_TEMPLATE_SEQ;
ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE ALTER COLUMN ID SET DEFAULT nextval('RM_DB_PRIVILEGE_TEMPLATE_SEQ');
ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_DB_PRIVILEGE_TEMPLATE_SEQ OWNED BY RM_DB_PRIVILEGE_TEMPLATE.ID;
ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE DROP COLUMN IF EXISTS VERSION;

CREATE SEQUENCE RM_DB_PRIVILEGE_TEMPLATE_ENTRY_SEQ;
ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE_ENTRY ALTER COLUMN ID SET DEFAULT nextval('RM_DB_PRIVILEGE_TEMPLATE_ENTRY_SEQ');
ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE_ENTRY ALTER COLUMN ID SET NOT NULL;
ALTER SEQUENCE RM_DB_PRIVILEGE_TEMPLATE_ENTRY_SEQ OWNED BY RM_DB_PRIVILEGE_TEMPLATE_ENTRY.ID;
ALTER TABLE RM_DB_PRIVILEGE_TEMPLATE_ENTRY DROP COLUMN IF EXISTS VERSION;









